[ profile ]
enableDev = true
addHype   = true
addPFP    = true
addBio    = true


[ data ]
username  = "devil" # blank = random
joinGuild = "MjTBsEA4uj" # invite code ~ blank = dont join
threads   = 10
debug     = true
showLockd = false


[ captcha ]
service  = "CAPSOLVER"
capKey   = 'CAI-B84C18E3DC8EA33F8E46E171B9E8C152'
